### ISSUE TITLE
#9 waypoint_updater.py - waypoints_tree has no query

### ISSUE THREAD

**Issue by stefancyliax** [stefancyliax/CarND-Capstone#10]
There is an error in waypoints_updater.py Zeile 63.

```
Traceback (most recent call last):
  File "/home/stefan/Documents/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 153, in <module>
    WaypointUpdater()
  File "/home/stefan/Documents/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 50, in __init__
    self.loop()
  File "/home/stefan/Documents/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 57, in loop
    self.publish_waypoints()
  File "/home/stefan/Documents/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 78, in publish_waypoints
    final_lane = self.generate_lane()
  File "/home/stefan/Documents/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 84, in generate_lane
    closest_idx = self.get_closest_waypoint_idx()
  File "/home/stefan/Documents/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 63, in get_closest_waypoint_idx
    closest_idx = self.waypoints_tree.query([x,y], 1)[1]
AttributeError: 'NoneType' object has no attribute 'query'
```

**Comment by stefancyliax** [comment]
Fixed
