### ISSUE TITLE
Bug: Cannot load frozen_sim_mobile-5000/optimized_inference_graph.pb with TF 1.3

### ISSUE THREAD

**Issue by paul-michalik** [stefancyliax/CarND-Capstone#24]
```
Traceback (most recent call last):
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 186, in <module>
    TLDetector()
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 47, in __init__
    self.light_classifier = TLClassifier(rospy.get_param("/path_to_graph"))
  File "/capstone/ros/src/tl_detector/light_classification/tl_classifier.py", line 15, in __init__
    self.impl = impl.tl_classifier.TLClassifier(path_to_graph)
  File "/capstone/ros/src/tl_detector/light_classification/impl/tl_classifier.py", line 39, in __init__
    self.graph, self.config = TLClassifier._init_graph(path_to_graph)
  File "/capstone/ros/src/tl_detector/light_classification/impl/tl_classifier.py", line 24, in _init_graph
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 406, in import_graph_def
    node, 'Input tensor %r %s' % (input_name, te)))
ValueError: graph_def is invalid at node u'ToFloat': Input tensor 'image_tensor:0' Cannot convert a tensor of type float32 to an input of type uint8.
```

**Comment by stefancyliax** [comment]
I think this was just a test. Since performance is fine now, i wouldn't invest any more time in this.
If nobody disagrees, I'll remove the model from the master branch. @fkeidel?

**Comment by fkeidel** [comment]
Das Skript optimize_for_inference.py, das ich benutzt, soll habe Macken hat. Es wird empfohlen, das neuere "graph_transform" zu verwenden.
Da das Projekt jetzt bei Stefan mit GPU läuft, sieht es so aus, als würden wir keine weitere Optimierung brauchen.
