### ISSUE TITLE
Images on /image_color cannot be processed in styx bridge 

### ISSUE THREAD

**Issue by paul-michalik** [stefancyliax/CarND-Capstone#6]
When running in Docker container built from image provided by Udacity the attempt to run the simulator with camera data raises an error: 

> ```
> message handler error
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 398, in _trigger_event
> return self.handlersevent
> File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 509, in _handle_eio_message
> self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
> File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 448, in _handle_event
> self._handle_event_internal(self, sid, data, namespace, id)
> File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 451, in _handle_event_internal
> r = server._trigger_event(data[0], namespace, sid, *data[1:])
> File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 480, in _trigger_event
> return self.handlers[namespace]event
> File "/capstone/ros/src/styx/server.py", line 58, in image
> bridge.publish_camera(data)
> File "/capstone/ros/src/styx/bridge.py", line 180, in publish_camera
> image_message = self.bridge.cv2_to_imgmsg(image_array, encoding="rgb8")
> File "/opt/ros/kinetic/lib/python2.7/dist-packages/cv_bridge/core.py", line 248, in cv2_to_imgmsg
> img_msg.height = cvim.shape[0]
> IndexError: tuple index out of range
> ```

**Comment by paul-michalik** [comment]
An upgrade of pillow fixes the problem see also  [#107](https://github.com/udacity/CarND-Capstone/issues/107) . Will update `Pillow` to version 5.0.0 in `requirement.txt`. Quick fix: run `pip install Pillow` in the container and restart `roslaunch launch\styx.launch`
